Models/Eleve.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ServiceEleve;

namespace EnsatGestion.Models
{
    [Serializable]
    public class Eleve 
    {
        public string cne { get; set; }
        public string prenom { get; set; }
        public string nom { get; set; }
        public string email { get; set; }
        public string filiere { get; set; }
        public string tel { get; set; }

        
    }
}

Controllers/EleveController.cs
using EnsatGestion.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Data;
using System.Xml.Linq;

namespace EnsatGestion.Controllers
{
    public class EleveController : Controller
    {

        ServiceEleve.Service1Client eleve = new ServiceEleve.Service1Client();
        public IActionResult Index()
        {
            return View("CreateEleve");
        }
        [HttpPost]
        public IActionResult Create(Eleve E)
        {
            eleve.Insert(E.cne,E.nom,E.prenom,E.email,E.filiere,E.tel);
            return RedirectToAction("Index");
        }
        public IActionResult List()
        {
            var Eleve = eleve.GetAll();
            ViewBag.Eleves = eleve.GetAll();
            return View("ListEleve");
        }

        public IActionResult getOne()
        {
            //var Eleve = eleve.GetAll();
            ViewBag.Eleve = eleve.GetAll().Nodes[1].ToString();

            return View("DetailsEleve");
        }
    }
}

Views/Eleve/CreateEleve.cshtml
@model EnsatGestion.Models.Eleve

@{
    ViewData["Title"] = "CreateEleve";
}

<h1>CreateEleve</h1>

<h4>Eleve</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Eleve" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="cne" class="control-label"></label>
                <input asp-for="cne" name="cne" class="form-control" />
                <span asp-validation-for="cne" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="prenom" class="control-label"></label>
                <input asp-for="prenom" class="form-control" />
                <span asp-validation-for="prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nom" class="control-label"></label>
                <input asp-for="nom" class="form-control" />
                <span asp-validation-for="nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="filiere" class="control-label"></label>
                <input asp-for="filiere" class="form-control" />
                <span asp-validation-for="filiere" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tel" class="control-label"></label>
                <input asp-for="tel" class="form-control" />
                <span asp-validation-for="tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Eleve/DetailsEleve.cshtml
@model EnsatGestion.Models.Eleve

@{
    ViewData["Title"] = "DetailsEleve";
}

<h1>DetailsEleve</h1>

<div>
    <h4>Eleve</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cne)
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.Eleve
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.filiere)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.filiere)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tel)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Eleve/ListEleve.cshtml
@model IEnumerable<EnsatGestion.Models.Eleve>

@{
    ViewData["Title"] = "ListEleve";
}

<h1>ListEleve</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.cne)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.filiere)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in ViewBag.Eleves) {
        <tr>
            <td>
                @item.cne
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.filiere)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tel)
            </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>